# Generated by Django 2.2.5 on 2020-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '归档', 'verbose_name_plural': '归档'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '添加标签', 'verbose_name_plural': '添加标签'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='归档'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='标签'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
