# Generated by Django 2.2.5 on 2020-03-14 07:34

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200311_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
