# Generated by Django 2.2.5 on 2020-04-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200414_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/images/blog_img/', verbose_name='封面'),
        ),
    ]
