# Generated by Django 2.2.5 on 2020-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200311_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
